extend class UaS_Consumable {
	// Add items to the package contents list
	void AddItem(name FoodItem, int quantity = 1) {
		bPACKAGED = true;
		if (!HDCore.CheckClassExists(FoodItem)) {
			A_Log(string.format("\ci%s: Invalid class '%s'! Ignoring...", GetClassName(), FoodItem));
			return;
		}
		for (int i = 1; i <= quantity; i++) {
			FoodList.push(FoodItem);
			NiceFoodList.push(GetDefaultByType((Class<Actor>)(FoodItem)).getTag());
		}
	}
}
